# Generated by Django 5.1.5 on 2025-02-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_signdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetail',
        ),
    ]
