# Generated by Django 5.1.5 on 2025-02-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_delete_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signdetail',
            old_name='cpassword',
            new_name='Cpassword',
        ),
        migrations.RenameField(
            model_name='signdetail',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='signdetail',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='signdetail',
            old_name='password',
            new_name='Password',
        ),
    ]
