# Generated by Django 5.1.5 on 2025-02-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_contactdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('appointmentDate', models.DateField()),
                ('services', models.CharField(max_length=400)),
                ('timeSlot', models.DateField()),
            ],
        ),
    ]
