# Generated by Django 5.1.5 on 2025-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0006_bookingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='timeSlot',
            field=models.CharField(max_length=100),
        ),
    ]
