# Generated by Django 5.1.5 on 2025-02-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0008_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feed',
        ),
    ]
