# Generated by Django 5.1.5 on 2025-02-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0009_rename_feedback_feedback_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feed',
            new_name='message',
        ),
    ]
