# Generated by Django 5.1.5 on 2025-02-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0010_rename_feed_feedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.IntegerField()),
            ],
        ),
    ]
